// <auto-generated />
using System;
using CitiesManager.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230618192900_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Core.Entities.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("b9bc23f6-e88d-4de3-aa20-c7a1b33e7f0c"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityID = new Guid("ed760560-e2aa-4c42-9932-085cc3a252de"),
                            CityName = "London"
                        },
                        new
                        {
                            CityID = new Guid("0235b75e-479c-4554-a59b-8b2ced2eebca"),
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityID = new Guid("5952ebc3-b5a0-4bfb-9a31-73adc581cff6"),
                            CityName = "Chicago"
                        },
                        new
                        {
                            CityID = new Guid("a7e4857b-1309-4fd8-8c61-439229e67e7a"),
                            CityName = "Houston"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
